name: Generate CICD Zip
on:
  pull_request:
    paths:
        - 'template/{{.input_root_dir}}/.github/workflows/{{.input_project_name}}**'
        - 'template/{{.input_root_dir}}/.azure/devops-pipelines/{{.input_project_name}}**'

defaults:
  run:
    working-directory: template/{{.input_root_dir}}


jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
      - name: Generate CICD Zip
        run: |
          cp --parents .github/workflows/\{\{.input_project_name\}\}-* cicd/template
          cp --parents .azure/devops-pipelines/\{\{.input_project_name\}\}-* cicd/template
          tar -czvf cicd.tar.gz cicd
      - name: Add Zip to Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "eng-ml-productionization@databricks.com"
          git add cicd.tar.gz
          git commit -m "Add CICD Zip to Pull Request"
          git push